data_example = [{'timestamp': '2018-09-15T17:50:07.939576',
                 'stock_symbol': 'TEST',
                 'shares': 10,
                 'indicator': 'buy',
                 'price': 120},
                {'timestamp': '2018-09-15T17:45:07.939576',
                 'stock_symbol': 'TEST',
                 'shares': 10,
                 'indicator': 'buy',
                 'price': 105},
                {'timestamp': '2018-09-15T17:42:07.939576',
                 'stock_symbol': 'TEST',
                 'shares': 10,
                 'indicator': 'buy',
                 'price': 106},
                {'timestamp': '2018-09-15T17:40:07.939576',
                 'stock_symbol': 'TEST',
                 'shares': 10,
                 'indicator': 'buy',
                 'price': 100},
                {'timestamp': '2018-09-15T17:37:07.939576',
                 'stock_symbol': 'TEST',
                 'shares': 10,
                 'indicator': 'buy',
                 'price': 102},
                {'timestamp': '2018-09-15T17:35:07.939576',
                 'stock_symbol': 'TEST',
                 'shares': 10,
                 'indicator': 'buy',
                 'price': 115},
                {'timestamp': '2018-09-15T17:30:07.939576',
                 'stock_symbol': 'TEST',
                 'shares': 10,
                 'indicator': 'buy',
                 'price': 120}]

stocks_example_dict = [{'TEA': {'type': 'common',
                                'last_dividend': 0,
                                'fixed_dividend': None,
                                'par_value': 100}},
                       {'POP': {'type': 'common',
                                'last_dividend': 8,
                                'fixed_dividend': None,
                                'par_value': 100}},
                       {'ALE': {'type': 'common',
                                'last_dividend': 23,
                                'fixed_dividend': None,
                                'par_value': 60}},
                       {'GIN': {'type': 'preferred',
                                'last_dividend': 8,
                                'fixed_dividend': 2,
                                'par_value': 100}},
                       {'JOE': {'type': 'common',
                                'last_dividend': 13,
                                'fixed_dividend': None,
                                'par_value': 250},
                        }]
